apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: semantic-extractor
  name: semantic-extractor
spec:
  ports:
  - name: "semantic"
    port: 1880
    targetPort: 1880
  selector:
    app: semantic-extractor